-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxka5Ct6gx8P16ozM
FEhTDx/hciwb5GCEM6T28RaIdcugCgYIKoZIzj0DAQehRANCAAQW8bL7giPoVH3A
O3/XfmPdWFNR+FngFfrA8dACaGEqsYPqWvDEZI6Phynyt11EqyaEydhkEtmtYxit
MIQX3vGL
-----END PRIVATE KEY-----